#! /usr/bin/python


import fileinput
import time
import sys

count =0

for line in fileinput.input():
	print line
	sys.stdout.flush()
	time.sleep(0.001)
	count = count + 1
	if count % 100000 == 0:
		time.sleep(0.1)

